modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="jaams_archeology"
version="1.0.0"
displayName="Jaam's Archeology"
displayURL="https://linktr.ee/jaamleeto"
logoFile="jaams_archeology_banner.png"
authors="Jaamleeto"
description="Jaams Archeology is a mod focused on expanding archaeology. Discover ancient artifacts, unearth hidden treasures."
issueTrackerURL="https://linktr.ee/jaamleeto"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.jaams_archeology]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.jaams_archeology]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
[modproperties."jaams_archeology"]
catalogueItemIcon="jaams_archeology:broken_sword_fragment"
catalogueBackground="jaams_archeology_background.png"
configuredBackground="minecraft:textures/block/spruce_planks.png"
# End of user code block dependencies configuration
